2021-01-14 21:08:46,539 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-14 21:12:41,873 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-14 21:19:31,919 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-14 21:19:37,057 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-14 21:20:00,024 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-14 21:22:55,253 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 09:19:00,739 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 09:24:06,253 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 09:24:30,377 ERROR: Exception on /user/bill [GET] [in /home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/whzheng/flask/microblog/app/routes.py", line 76, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/whzheng/flask/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/whzheng/flask/microblog/app/templates/base.html", line 28, in top-level template code
    {% block content %}{% endblock %}
  File "/home/whzheng/flask/microblog/app/templates/user.html", line 17, in block "content"
    {{ form.hidden_tag() }}
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-01-15 09:33:24,682 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 09:38:30,821 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 09:40:02,268 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 09:47:16,126 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 09:53:11,162 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 09:53:14,095 ERROR: Exception on /index [GET] [in /home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/whzheng/flask/microblog/app/routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form, posts=posts)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/whzheng/flask/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/whzheng/flask/microblog/app/templates/base.html", line 12, in top-level template code
    <a href="{{ url_for('explor') }}">Explore</a>
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explor'. Did you mean 'explore' instead?
2021-01-15 09:55:06,946 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 10:00:53,591 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 10:05:24,351 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 10:05:44,948 ERROR: Exception on /explore [GET] [in /home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/whzheng/flask/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/whzheng/flask/microblog/app/routes.py", line 47, in explore
    return render_template('index.html', title='Home', form=form,
NameError: name 'form' is not defined
2021-01-15 10:07:26,298 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
2021-01-15 10:11:23,753 INFO: Microblog startup [in /home/whzheng/flask/microblog/app/__init__.py:42]
